### ISSUE TITLE
Exception reported: Entity -1 (-1) is invalid

### ISSUE THREAD

**Issue by Septembers** [Natanel-Shitrit/Rare-Animation-Controller#1]
hello

Title: [CS:GO] Rare Animation Controller (Tweaks the usage of rare weapon animations.)
  Author: Natanel 'LuqS', KoNLiG
  Version: 1.0.3

L 09/23/2021 - 00:03:43: [SM] Exception reported: Entity -1 (-1) is invalid
L 09/23/2021 - 00:03:43: [SM] Blaming: RareAnimationController.smx
L 09/23/2021 - 00:03:43: [SM] Call stack trace:
L 09/23/2021 - 00:03:43: [SM]   [0] GetEntPropEnt
L 09/23/2021 - 00:03:43: [SM]   [1] Line 222, d:\Programming\SourcePawn\Plugins\GitHub Repositories\My Repositories\Rare-Animation-Controller\scripting\RareAnimationController.sp::LoadWeaponSequences
L 09/23/2021 - 00:03:43: [SM]   [2] Line 151, d:\Programming\SourcePawn\Plugins\GitHub Repositories\My Repositories\Rare-Animation-Controller\scripting\RareAnimationController.sp::OnPlayerRunCmdPost

**Comment by Natanel-Shitrit** [comment]
Was fixed in ad301f5.
