### ISSUE TITLE
Engine Error: Host_Error: Bad String

### ISSUE THREAD

**Issue by peeplmao** [Natanel-Shitrit/Rare-Animation-Controller#2]
I'm new to CSGO servers and maybe its my server that is glitching but every time I try to launch the server with the plugin on, the server crashes with this message

![image](https://user-images.githubusercontent.com/108683315/177181779-cc1fb4c9-b5fb-412b-9f66-35d30996b4b7.png)

**Comment by KoNLiG** [comment]
Seems like this issue is unrelated to Rare-Animation-Controller.
Please feel free to open another issue if this is still happening.
